spring.application.name=test


db.url=jdbc:sqlserver://localhost:1433;databaseName=PI;encrypt=true;trustServerCertificate=true
db.username=PIUser
db.password=pcp.2011
db.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver